import React from "react";
import { Col, Row } from "react-bootstrap";
import "./HomePage.css";
import { SERVICECONTENTS } from "../Services/ServiceContent";
import ServiceCard from "../Services/ServiceCard";
import Slider from "../../components/Slider/Slider";
import corImage from "../../asset/coe.png";
import aboutImage from "../../asset/about_kran.jpg";
import cmmilogo from "../../asset/cmmi logo.png";
import iso9001logo from "../../asset/iso 9001 logo.png";
import iso20100logo from "../../asset/iso 20100 logo.png";
import iso27001logo from "../../asset/iso 27001 logo.png";
import Footer from "../../components/Footer/Footer";

const certifications = [
  { image: cmmilogo, alt: "cmmilogo" },
  { image: iso9001logo, alt: "iso9001logo" },
  { image: iso20100logo, alt: "iso20100logo" },
  { image: iso27001logo, alt: "iso27001logo" },
];

const flagshipContent = [
  {
    link: (
      <iframe
        src="https://www.youtube.com/embed/_xZIaWY0sGA"
        width="100%"
        height="100%"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen
      ></iframe>
    ),
    heading: "KRAN Profile",
    discription:
      "25 years of experience working on Transformational Projects in the Government Sector",
  },
  {
    link: (
      <iframe
        src="https://www.youtube.com/embed/61vBfSVcjBc"
        width="100%"
        height="100%"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen
      ></iframe>
    ),
    heading: "e-Budget",
    discription:
      "Journey from a manual budget to India's first completely Digital Budget available on Google PlayStore",
  },
  {
    link: (
      <iframe
        src="https://www.youtube.com/embed/wjwk8uG6-EE"
        width="100%"
        height="100%"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen
      ></iframe>
    ),
    heading: "KRAN Galaxy",
    discription: "An Integrated Application LifeCycle Management System",
  },
];

function HomePage() {
  return (
    <div className="home">
      <Slider />
      <div className="homepage">
        <section className="flagship">
          <h2 className="head">Flagship Offerings</h2>
          <Row>
            {flagshipContent.map((flagship) => (
              <Col xs={12} md={4} xl={4}>
                <div className="youtubeContent">
                  <div className="youtubeLinks">{flagship.link}</div>
                  <p style={{color:"#c80808"}}>
                    <b>{flagship.heading}</b>
                  </p>
                  <p style={{fontSize:"small"}}>
                    {flagship.discription}
                  </p>
                </div>
              </Col>
            ))}
          </Row>
        </section>
        <section className="coe">
          <h2 className="head">Centres Of Excellence</h2>
          <Row className="coe-content">
            <Col
              xs={12}
              md={6}
              xl={6}
              style={{ textAlign: "center"}}
            >
              <img src={corImage} alt="corImage" className="coeImage" />
            </Col>
            <Col xs={12} md={6} xl={6} style={{ textAlign: "justify" }}>
              <h4 style={{ color: "#006adb" }}>Exclusive Domain Focus</h4>
              <p>
                We aim to combine our technical and domain expertise with inputs
                from external subject matter experts, to catalyze transformation
                in Public Administration. These experts are committed to
                disseminate knowledge and share best practices across the
                organization. Each CoE will continually strive to achieve
                excellence in its respective domain, the success of which, will
                be measured by the Solution and Process Improvements brought
                into the respective domains.
              </p>
              <p>
                👉 <b>Public finance</b> - Public Finance Management has been
                identified as a key area of reform for efficient public service
                delivery and creation of wealth and employment.
              </p>
              <p>
                👉 <b>Licensing & Compliance</b> - Licensing and Compliance
                ensures how effectively acts and rules introduced by Governments
                can be enforced. It can be a major contributor towards the
                revenue generated by Governments.
              </p>
              <p>
                👉 <b>General Administration</b> - it is the planning,
                organizing, directing, coordinating and controlling of general
                operations of an organization.
              </p>
              <p>
                👉 <b>Direct Benefit Transfer</b> - it is the process of
                transferring benefits such as grants, subsidies etc. directly to
                the people through their bank/ Post office accounts.
              </p>
            </Col>
          </Row>
        </section>
        <section className="aboutus">
          <h2 className="head">About Us</h2>
          <Row className="coe-content">
            <Col xs={12} md={6} xl={6} style={{ textAlign: "center" }}>
              <img src={aboutImage} alt="aboutImage" className="coeImage" />
            </Col>
            <Col xs={12} md={6} xl={6} style={{ textAlign: "justify" }}>
              <p>
                Over the last 25 years, KRAN has focused exclusively on the
                Government Sector and has been involved in multiple mission
                critical projects across the country. KRAN has been involved in
                many Transformational Projects in the Government Sector,
                impacting and uplifting the life of the target segments.
              </p>
              <p>
                Our major clients include Departments in Various State
                Governments and Central Government, State / Central PSUs,
                Projects funded by WHO, Asian Development Bank and World Bank.
              </p>
              <h4 style={{ color: "#01485e" }}>
                <b>Our Focus</b>
              </h4>
              <p>
                👉 Strengthen the collective and consultative decision-making
                process. <br />
                👉 Simplifying complexities of decision making without
                compromise. <br />
                👉 Bring changes through automation without existing processes.{" "}
                <br />
                👉 Ensure traceability and transparency in decisions.
                <br />
                👉 Transfer the benefits derived from technology enabled
                governance.
              </p>
              <Row>
                {certifications.map((certifiImage) => (
                  <Col xs={12} md={3} xl={3}>
                    <img
                      src={certifiImage.image}
                      alt={certifiImage.alt}
                      className="certifiImage"
                    />
                  </Col>
                ))}
              </Row>
            </Col>
          </Row>
        </section>
        <section className="services">
          <h2 className="head">Services</h2>
          <p className="para">
            We have the ability to work closely with our clients to understand
            and accurately identify problem areas and suggest simple but
            effective solutions. The belief that technology is only a means to
            the solution and not the solution itself forms the essence of our
            work culture.
          </p>
          <Row>
            {SERVICECONTENTS.map((content) => (
              <Col xs={12} md={4} xl={4}>
                <ServiceCard data={content} />
              </Col>
            ))}
          </Row>
        </section>
      </div>
      <Footer />
    </div>
  );
}

export default HomePage;
